#define DOUBLE_MAX_MOVE_DISTANCE 100
#define MAX_HEIGHT_LEVEL 3
#define MAX_ASTAR_ARRAY_LENGTH DOUBLE_MAX_MOVE_DISTANCE*DOUBLE_MAX_MOVE_DISTANCE*MAX_HEIGHT_LEVEL
#define MAX_CLOUD_DIM 10
#define UI_Z_POS 0
#define MAX_PARTICLE_LIFETIME 3
#define TIME_TILL_HOUSE_BURNS 5
#define TIME_TILL_CASTLE_BURNS 8
#define RENDER_Z 10
#define CLOUDS_RENDER_Z 4
#define BACKGROUND_COLOR make_float4(0.278, 0.671, 0.663, 1.0)
#define TILE_WIDTH_PIXELS 64
#define CHUNK_DIM 16
#define CHUNK_REVEAL_MARGIN CHUNK_DIM
#define RENDER_DISTANCE 3
#define DAYLIGHT_SPEED (1.0f/(60.0f*24.0f))
#define MAX_FADE_TIME 3

